/** Declaration file generated by dts-gen */
declare module 'react-komposer' {
  export function compose(dataLoader: any, ...args: any[]): any;

  export function composeAll(...args: any[]): any;

  export function merge(...args: any[]): any;

  export function setDefaults(...args: any[]): any;

  export function setStubbingMode(mode: any): void;

  export function stub(Comp: any, fn: any): void;

  export namespace compose {
      const prototype: {
      };

  }

  export namespace composeAll {
      const prototype: {
      };

  }

  export namespace merge {
      const prototype: {
      };

  }

  export namespace setDefaults {
      const prototype: {
      };

  }

  export namespace setStubbingMode {
      const prototype: {
      };

  }

  export namespace stub {
      const prototype: {
      };

  }
}